### ISSUE TITLE
Feature Request: Show only true date possibilities.

### ISSUE THREAD

**Issue by natgross** [mendelg/cupertino_hebrew_date_picker#2]
The picker should show "אדר ב" only when applicable. Same for יום ל.
Using the kosher dart api, it is easy, because it has boolean getters that tell you if year is leap, also if there are 30 days in that particular month for the specific year. You simply show different lists (or modify the underlying list) based on onChanged / setState.

**Comment by mendelg** [comment]
Thank you for this proposal.

with the latest version, it now only shows true possible dates!

**Comment by mendelg** [comment]
@natgross Thank you for this proposal.

with the latest version, it now only shows true possible dates!
